services:
  postgres:
    image: postgres:15-alpine
    container_name: tatva_db
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: tatva_dev
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: tatva
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tatva_dev" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: medusa-redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
